crm/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.static import serve
from app01 import views

#滑动模块验证码要导入的包
from app01.views import pcgetcaptcha
# from app01.views import pcvalidate
from app01.views import pcajax_validate
from app01.views import mobileajax_validate
from app01.views import home


urlpatterns = [
    url(r'^stu/quest/(\d+)/(\d+)/$',views.score),
    url(r'^student_login/$', views.student_login),
    url(r'^question/(\d+)/$', views.question),
    url(r'^admin/',admin.site.urls),
    url(r'^login/', views.login),
    url(r'^index/',views.index),
    url(r'^questionnaireEditor/',views.questionEditor),
    url(r'^questionnaireAdd/',views.questionnaireAdd),
    url(r'^getvalicode/',views.getvalicode),
    # 滑动模块验证码URL
    url(r'^pc-geetest/register',pcgetcaptcha, name='pcgetcaptcha'),
    url(r'^pc-geetest/ajax_validate',pcajax_validate, name='pcajax_validate'),
    url(r'/*', home, name='home'),
]

app01/models.py
from django.db import models
# Create your models here.
from django.db import models

class UserInfo(models.Model):

    name = models.CharField(max_length=32,verbose_name="用户名")
    pwd = models.CharField(max_length=32,verbose_name="密码")

    class Meta:
        verbose_name_plural="用户信息表"
    def __str__(self):
        return self.name

class ClassList(models.Model):

    name = models.CharField(max_length=32,verbose_name="班级")

    class Meta:
        verbose_name_plural="班级表"

    def __str__(self):
        return self.name

class Student(models.Model):

    name = models.CharField(max_length=32,verbose_name="学生名")
    pwd = models.CharField(max_length=32,verbose_name="密码")
    classes = models.ForeignKey(verbose_name="所属班级",to=ClassList)

    class Meta:
        verbose_name_plural="学生表"

    def __str__(self):
        return self.name

class Questionnaire(models.Model):

    name = models.CharField(max_length=32)
    creator = models.ForeignKey(verbose_name="创建者",to=UserInfo)
    cls = models.ForeignKey(verbose_name="所属班级",to=ClassList)

    class Meta:
        verbose_name_plural="调查问卷表"

    def __str__(self):
        return self.name

class Question(models.Model):

    name = models.CharField(max_length=100)
    question_types=(
        (1,"打分(1-10分)"),
        (2,"单选"),
        (3,"建议"),
    )
    type = models.IntegerField(choices=question_types,verbose_name="问题类型")
    Questionnaire=models.ForeignKey(verbose_name="调查问卷",to=Questionnaire)

    class Meta:
        verbose_name_plural="问题表"

    def __str__(self):
        return self.name

class Option(models.Model):

    name = models.CharField(max_length=32,verbose_name="名称")
    score = models.IntegerField(verbose_name="选项对应的分值")
    question = models.ForeignKey(verbose_name="所属问题",to=Question)

    class Meta:
        verbose_name_plural="选项表"

    def __str__(self):
        return self.name

class Answer(models.Model):

    student = models.ForeignKey(verbose_name="学生",to=Student)
    question = models.ForeignKey(verbose_name="所属问题",to=Question)
    val = models.IntegerField(null=True,blank=True,verbose_name="评分值")
    content = models.CharField(max_length=255,null=True,blank=True,verbose_name="评论")
    option = models.ForeignKey(verbose_name="选项",to=Option,null=True,blank=True)

    class Meta:
        verbose_name_plural="回复表"

    def __str__(self):
        return self.content

templates/index.html
{% extends "models.html" %}

{% block content-title %}
   首页/数据列表
{% endblock content-title %}

{% block content %}
<a href="/questionnaireAdd/">
    <button type="button" class="btn btn-primary">
      添加
    </button>
</a>
<p></p>
<table class="table table-bordered">
    <thead>
    <th>调查问卷名称</th>
    <th>调查问卷班级</th>
    <th>参与人数</th>
    <th>问卷选项</th>
    <th>调查地址</th>
    <th>查看评分</th>
    <th>操作</th>
    </thead>
    <tbody>
    {% for Questionnaire in Questionnaire_list %}
        <tr>
            <td>{{ Questionnaire.name }}</td>
            <td>{{ Questionnaire.cls.name }}</td>
            <td>{{ Questionnaire.cls.student_set.count }}</td>
            <td><a href="/question/{{ Questionnaire.id }}/">编辑问卷</a></td>
            <td><a href="/stu/quest/{{ Questionnaire.id }}/{{ Questionnaire.cls.id }}/">/stu/quest/{{ Questionnaire.id }}/{{ Questionnaire.cls.id }}/</a></td>
            <td>查看评分</td>
            <td>删除</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock content %}

templates/login.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <META http-equiv=Content-Type content="text/html; charset=gb2312">
    <title>用户登录</title>
    <script type="application/javascript" src="/static/jquery-3.2.1.min.js"></script>
    <script type="application/javascript" src="/static/jquery.session.js"></script>
    <script type="application/javascript" src="/static/bootstrap3/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/bootstrap3/css/bootstrap.min.css">
    <script type="application/javascript" src="/static/jquery.cookie.js"></script>
    <link rel="stylesheet" href="/static/bootstrap3/css/bootstrap-theme.min.css">
    <script src="http://static.geetest.com/static/tools/gt.js"></script>
    <style type="text/css">
        #embed-captcha {
            width: 300px;
            margin: 0 auto;
        }
        .show {
            display: block;
        }
        .hide {
            display: none;
        }
        #notice {
            color: red;
        }
        /* 以下遮罩层为demo.用户可自行设计实现 */
        #mask {
            display: none;
            position: fixed;
            text-align: center;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.5);
            overflow: auto;
        }
        /* 可自行设计实现captcha的位置大小 */
        .popup-mobile {
            position: relative;
        }
        #popup-captcha-mobile {
            position: fixed;
            display: none;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
            -webkit-transform: translate(-50%, -50%);
            z-index: 9999;
        }
    </style>
</head>
<body style="background-color:#eee">
<div class="container" style="margin-top: 100px">
    <div class="row col-md-4 col-md-offset-4">
        <div class="h3 col-md-offset-3">用户登陆</div>
{#        <p class="loginerror text-center text-danger hide">用户名或密码错误!</p>#}
    </div>
    <div class="row col-md-8 col-md-offset-2">
        <form class="form-horizontal" method="post" action="/login/">
            {% csrf_token %}
            <div class="form-group">
                <label for="username" class="col-md-3 control-label lead">用户名</label>
                <div class="col-md-5">
                    {{ form.name }}
                </div>
                <div class="col-md-4">
                    <span class="username text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="col-md-3 control-label lead">密&nbsp;&nbsp;码</label>
                <div class="col-md-5">
                    {{ form.pwd }}
                </div>
                <div class="col-md-4">
                    <span class="password text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label for="validcode" class="col-md-3 control-label lead">验证码</label>
                <div class="col-md-5">
                    <div class="col-md-6" style="padding-left: 0px">
                        <input type="text" class="input-lg form-control" id="validCode" name="validCode">
                    </div>
                    <div class="col-md-6 text-right">
                        <img src="/getvalicode/" id="validcode" alt="" width="110px" height="45px">
                    </div>
                </div>
                <div class="col-md-4">
                    <span class="validcode text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                    <a href="/register/">用户注册</a>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-5">
                    <button type="button" class="btn btn-lg btn-primary btn-block login">登陆</button>
                </div>
            </div>
        </form>
    </div>
    <div id="popup-captcha"></div>
</div>
<script type="application/javascript">

    function addhide() {
        $(".username").addClass("hide")
        $(".password").addClass("hide")
        $(".validcode").addClass("hide")
    }

    $("#validcode").click(function () {
        this.src+="?"
    })


 //滑动验证码框
   var handlerPopup = function (captchaObj) {
        // 成功的回调
        captchaObj.onSuccess(function () {
            var validate = captchaObj.getValidate();
            $.ajax({
                url: "/pc-geetest/ajax_validate", // 进行二次验证
                type: "post",
{#                dataType: "json",#}
                headers:{"X-CSRFToken":$.cookie('csrftoken')},
                data: {
                    name: $('#username').val(),
                    pwd: $('#password').val(),
                    validCode:$('#validCode').val(),
                    geetest_challenge: validate.geetest_challenge,
                    geetest_validate: validate.geetest_validate,
                    geetest_seccode: validate.geetest_seccode
                },
                success: function (data) {
                    if (data=="true") {
                        //未登陆时如果有历史记录就直接跳转到之前的页面
                        if($.session.get("history_url")){
                            window.location.href =$.session.get("history_url")
                        }else{
                            window.location.href ="/index/";
                        }

                    } else {
                        data=JSON.parse(data);
                        $(".username").removeClass("hide");
                        $(".password").removeClass("hide");
                        $(".validcode").removeClass("hide");
                        $(".username").html(data.username);
                        $(".validcode").html(data.validCode);
                        $(".password").html(data.__all__);
                        setTimeout(addhide,10000)
                    }
                }
            });
        });
        $(".login").click(function () {
            captchaObj.show();
        });
        // 将验证码加到id为captcha的元素里
        captchaObj.appendTo("#popup-captcha");
        // 更多接口参考：http://www.geetest.com/install/sections/idx-client-sdk.html
    };
    // 验证开始需要向网站主后台获取id，challenge，success（是否启用failback）
    $.ajax({
        url: "/pc-geetest/register?t=" + (new Date()).getTime(), // 加随机数防止缓存
        type: "get",
        headers:{"X-CSRFToken":$.cookie('csrftoken')},
        dataType: "json",
        success: function (data) {
            // 使用initGeetest接口
            // 参数1：配置参数
            // 参数2：回调，回调的第一个参数验证码对象，之后可以使用它做appendTo之类的事件
            initGeetest({
                gt: data.gt,
                challenge: data.challenge,
                product: "popup", // 产品形式，包括：float，embed，popup。注意只对PC版验证码有效
                offline: !data.success // 表示用户后台检测极验服务器是否宕机，一般不需要关注
                // 更多配置参数请参见：http://www.geetest.com/install/sections/idx-client-sdk.html#config
            }, handlerPopup);
        }
    });


</script>
</body>
</html>

templates/models.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <META http-equiv=Content-Type content="text/html; charset=gb2312">
    <title>
    {% block title %}
        文章管理
    {% endblock %}
    </title>
    <script type="application/javascript" src="/static/jquery-3.2.1.min.js"></script>
    <script type="application/javascript" src="/static/bootstrap3/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/bootstrap3/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap3/css/bootstrap-theme.min.css">
    <script type="application/javascript" src="/static/jquery.cookie.js"></script>

    <!--  引入文本编辑器js -->
    <script charset="utf-8" src="/static/editor/kindeditor-all.js"></script>
    <script charset="utf-8" src="/static/editor/lang/zh-CN.js"></script>


</head>
<body>

{% block motai %}

{% endblock %}

<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">CRM 管理系统</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <!--
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      -->
      <ul class="nav navbar-nav navbar-right">
          {% if request.session.username %}
              <li><a href="#"><span class="glyphicon glyphicon-user" style="color: white"></span>{{ request.session.username }}</a></li>
              <li><a href="/index/"><span class="glyphicon glyphicon-home" style="color:white">主页</span></a></li>
              <li><a href="#"><span class="glyphicon glyphicon-off" style="color:white"></span>注销</a></li>
          {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-2">
            <div class="panel panel-primary">
              <div class="panel-heading text-center">
                <h3 class="panel-title">操作</h3>
              </div>
              <div class="panel-body text-center">
                {% block permissionManager%}
                <div class="panel panel-primary">
                  <div class="panel-heading">
                      <a href="/blog/{{ request.session.username }}/manager/" style="color: white;text-decoration: none">权限管理</a>
                  </div>
                </div>
                {% endblock permissionManager %}

                {% block clientManager %}
                <div class="panel panel-default">
                  <div class="panel-heading">
                      <a href="/blog/{{ request.session.username }}/manager/?action=category_manager" style="color: black;text-decoration: none">客户管理</a>
                  </div>
                </div>
               {% endblock clientManager %}

                {% block schoolManager %}
                <div class="panel panel-default">
                  <div class="panel-heading">
                      <a href="/blog/{{ request.session.username }}/manager/?action=tag_manager" style="color: black;text-decoration: none">校区管理</a>
                  </div>
                </div>
                {% endblock schoolManager %}

              {% block employeeManager %}
                <div class="panel panel-default">
                  <div class="panel-heading">
                      <a href="/blog/{{ request.session.username }}/manager/?action=tag_manager" style="color: black;text-decoration: none">校区管理</a>
                  </div>
                 <div class="panel-body">
                        <p>学校列表</p>
                        <p>课程列表</p>
                        <p>开班列表</p>
                        <p>学生列表</p>
                        <p>上课记录表</p>
                        <p>学生学习记录表</p>
                        <p><a href="/index/">调查问卷列表</a></p>
                  </div>
                </div>
                {% endblock employeeManager %}

            <!--
                 <div class="panel panel-default">
                  <div class="panel-heading">
                        用户管理
                  </div>
                 </div>
             -->
              </div>
            </div>
        </div>

        <!-- 主体部分 -->
        <div class="col-md-10">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title">
                  {% block content-title %}
                        Panel title
                  {% endblock content-title %}
                </h3>
              </div>
              <div class="panel-body">
                  {% block content %}
                        Panel content
                  {% endblock %}
              </div>
            </div>
        </div>
    </div>
</div>
</body>
{% block js %}

{% endblock js %}

{% block css %}

{% endblock css %}
</html>

templates/questionEditor.html
{% extends "models.html" %}

{% block content-title %}
    编辑问卷题目
{% endblock content-title %}

{% block css %}
<style type="text/css">
.hide{
    display: none;
}
ol {
    padding: 0;
    list-style: none;
    counter-reset: sectioncounter
}

ol > li:before {
    content: '问题' counter(sectioncounter) ':';
    counter-increment: sectioncounter;
    font-size: 18px;
    color: #d4d4d4;
}

ol > li:nth-of-type(odd) {
    background-color: #f9f9f9;
}
</style>

{% endblock css %}

{% block content %}
    <div class="row">
        <div class="col-md-offset-8 col-md-4 text-right">
            <button class="btn btn-success addProblem">添加</button>&nbsp;&nbsp;<button class="btn btn-primary updateProblem">保存</button>
        </div>
    </div>

<form action="">
<div class="problemBody" >
<div class="problem">
<ol class="problem-Body">
{% for item in form_list %}
    <li problemId="{{ item.obj.id }}">{{ item.form.name }} <span class="glyphicon glyphicon-remove deloption pull-right"></span>
    <div class="option-group">
    <p>类型: {{ item.form.type }}<a class="addOption {{ item.option_class }}">添加</a></p>
    {% for v in item.options %}
        <p class="optionId">名称: &nbsp;{{ v.form.name }} 分值:&nbsp;{{ v.form.score }}<span class="glyphicon glyphicon-remove deloption"></span>
            <input type="hidden" optionId="optionId" value="{{ v.obj.id }}">
        </p>
    {% endfor %}
    </div>
    <p><hr></p>
    </li>
{% endfor %}
</ol>
</div>
</div>
    <input type="hidden" name="Questionnaire_id" value="{{ Questionnaire_id }}">
</form>

{% endblock content %}

{% block js %}
<script type="application/javascript">

$(".problem").on("change","[name=type]",function () {
    if(this.value==2){
      $(this).next().removeClass("hide")
    }else{
      $(this).parent().nextAll().empty();
      $(this).next().addClass("hide")
    }
});

//声明选项的id让自增
opid=$("[optionid=optionId]").length;
$(".problem").on("click",".addOption",function () {
     if(opid==0){
         opid=1;
     }
     $(this).parent().parent().append('<p class="optionId">名称: &nbsp;<input type="hidden" optionId="optionId" value='+opid+'><input type="text" name="name"maxlength="32" required="" id="id_name" optionname="option"> 分值:&nbsp;<input type="number" name="score" required="" id="id_score"><span class="glyphicon glyphicon-remove deloption"></span></p>')
     opid=opid+1
});

$(".problem").on("click",".deloption",function () {
     $(this).parent().remove();
});

//在现有问题id上加1
$(".addProblem").click(function (){
    var pid=parseInt($("li").last().attr("problemid"))+1;
    $(".problem-Body").append('<li problemid='+pid+'><input type="text" name="name" maxlength="100" required="" id="id_name" questionname="name"><span class="glyphicon glyphicon-remove deloption pull-right"></span><div class="option-group"><p>类型: <select name="type" questiontype="type" required="" id="id_type"><option value="1" selected="">打分(1-10分)</option><option value="2">单选</option><option value="3">建议</option></select><a class="addOption hide">添加</a></p></div>'+
'<p></p><hr><p></p></li>');
});

$(".updateProblem").click(function () {

//拿到问题列表中所有的值
var result=[];
$("ol li").each(function(k,v){
    question_obj={};
    question_obj["Questionnaire_id"]=$("[name=Questionnaire_id]").val();
    question_obj["question_id"]=$(v).attr("problemId");
	question_obj["name"]=$(v).find("[name=name]").val();
    question_obj["type"]=$(v).find("[name=type]").val();
    var options=$(v).find("[optionname=option]");
    var scores=$(v).find("[id=id_score]");
    var optionid=$(v).find("[optionid=optionId]");

    question_obj["options"]=[];
    for(var i=0;i<options.length;i++){
    	question_obj["options"].push({"optionId":$(optionid).eq(i).val(),"optionName":$(options).eq(i).val(),"optionScore":$(scores).eq(i).val()})
    }
    result.push(question_obj)
});


    $.ajax({
        type:"POST",
        dataType:"json",
        headers:{"X-CSRFToken":$.cookie('csrftoken')},
        url:"/questionnaireAdd/",
        data:JSON.stringify({"result":result}),
        success:function (data) {
            console.log(data)
        }
    });
})

</script>
{% endblock js %}

templates/questionnaireAdd.html
{% extends "models.html" %}

{% block content-title %}
    添加问卷表
{% endblock content-title %}

{% block content %}
<div class="row">
    <div class="col-md-10">
<form class="form-horizontal">
  <div class="form-group">
    <label for="Questionnaire" class="col-sm-2 control-label">问卷名称</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="Questionnaire" placeholder="问卷名称" name="QuestionnaireName">
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">创建者:</label>
    <div class="col-sm-10">
     <select class="form-control" name="userid">
         {% for item in user_list %}
          <option value="{{ item.id }}">{{ item.name }}</option>
         {% endfor %}
        </select>
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">所属班级:</label>
    <div class="col-sm-10">
     <select class="form-control" name="classid">
         {% for item in class_list %}
            <option value="{{ item.id }}">{{ item.name }}</option>
         {% endfor %}
        </select>
    </div>
  </div>
</div>
</div>
<div class="row">
<div class="col-md-offset-4 col-md-8">
    <button type="button" class="btn btn-success addQuestionnaire">添加</button>&nbsp;&nbsp;<button class="btn btn-primary">保存</button>
</div>
</form>
</div>
{% endblock content %}

{% block js %}
<script type="application/javascript">

$(".addQuestionnaire").click(function () {

$.ajax({
   type: "POST",
   url: "/questionnaireAdd/",
   data: $("form").serialize(),
   success: function(data){
     console.log( "Data Saved: " + data );
     if(data=="true"){
        location.href="/index/"
     }
   }
});

});



</script>
{% endblock js %}

templates/score.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <style>
        ul{
            list-style-type: none;
        }
        ul li{
            display: inline-block;
        }
    </style>
</head>
<body>
    <div>
        <form method="post" action="/stu/quest/{{ qn_id }}/{{ classId }}/" novalidate>
            {% csrf_token %}
            {% for fd in form %}
                <div>
                    <p>{{ fd.label }} {{ fd.errors.0 }}</p>
                       {{ fd }}
                </div>
            {% endfor %}
            <input type="submit" value="提交">
        </form>
    </div>
</body>
</html>

templates/slogin.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <META http-equiv=Content-Type content="text/html; charset=gb2312">
    <title>学生登陆</title>
    <script type="application/javascript" src="/static/jquery-3.2.1.min.js"></script>
    <script type="application/javascript" src="/static/bootstrap3/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/bootstrap3/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap3/css/bootstrap-theme.min.css">
</head>
<body>
<div align="center">
    <form action="" method="post">
        {% csrf_token %}
        <p>登陆</p>
        <p>用户: <input type="text" name="student_name"></p>
        <p>密码: <input type="password" name="student_pass"></p>
        <p><button type="button">登陆</button></p>
    </form>
</div>
</body>
<script type="application/javascript" src="/static/jquery.cookie.js"></script>
<script type="application/javascript">

    $("button").click(function (){
        $.ajax({
            url:"/student_login/",
            headers:{"X-CSRFToken":$.cookie('csrftoken')},
            data:$("form").serialize(),
            type:"post",
            success:function(data){
                console.log(data)
                if(data=="true"){
                    location.href="/index/"
                }
            }
        })
    });

</script>
</html>